apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: falco
spec:
  project: default
  source:
    repoURL: ''
    targetRevision: HEAD
    chart: falco
    plugin:
      name: lovely
      env:
      - name: LOVELY_HELM_VALUES
        value: |
          - values-falco.yaml
          - values-sidecar.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
