apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: spark-master
  namespace: apache-spark
  template:
    spec:
      volumes:
      - name: certs
        secret:
          defaultMode: 420
          secretName: spark-crt-custom
